-- Flyway baseline for the verify tables, generated by db_scripts/generate_flyway_baseline.sh
-- from db_scripts/inji_certify/ddl. Do not edit: later schema changes are new versioned migrations.

-- ---- verify-authorization_request_details.sql ----
-- This Source Code Form is subject to the terms of the Mozilla Public
-- License, v. 2.0. If a copy of the MPL was not distributed with this
-- file, You can obtain one at https://mozilla.org/MPL/2.0/.
--
-- Table required by the embedded inji-verify library.
-- Stores VP authorization requests created during the presentation-during-issuance flow.

CREATE TABLE IF NOT EXISTS authorization_request_details (
    request_id      character varying(40) NOT NULL,
    transaction_id  character varying(40) NOT NULL,
    authorization_details text NOT NULL,
    expires_at      bigint NOT NULL,
    CONSTRAINT pk_authorization_request_details PRIMARY KEY (request_id)
);

COMMENT ON TABLE authorization_request_details IS 'Stores VP authorization request details created by the embedded inji-verify library';
COMMENT ON COLUMN authorization_request_details.request_id IS 'Unique request ID for the VP authorization request';
COMMENT ON COLUMN authorization_request_details.transaction_id IS 'Transaction ID linking this request to the issuance session';
COMMENT ON COLUMN authorization_request_details.authorization_details IS 'JSON blob containing full OpenID4VP authorization request details';
COMMENT ON COLUMN authorization_request_details.expires_at IS 'Epoch-millis expiry of the authorization request';

CREATE INDEX IF NOT EXISTS idx_ard_transaction_id ON authorization_request_details (transaction_id);

-- ---- verify-vc_submission.sql ----
-- This Source Code Form is subject to the terms of the Mozilla Public
-- License, v. 2.0. If a copy of the MPL was not distributed with this
-- file, You can obtain one at https://mozilla.org/MPL/2.0/.
--
-- Table required by the embedded inji-verify library.
-- Stores individual VC results extracted during VP verification.

CREATE TABLE IF NOT EXISTS vc_submission (
    transaction_id character varying(40) NOT NULL,
    vc             text NOT NULL
);

COMMENT ON TABLE vc_submission IS 'Stores individual VC results from VP verification by the embedded inji-verify library';
COMMENT ON COLUMN vc_submission.transaction_id IS 'Transaction ID linking the VC result to the issuance session';
COMMENT ON COLUMN vc_submission.vc IS 'Base64-encoded or JSON VC extracted from the verified VP token';

CREATE INDEX IF NOT EXISTS idx_vc_submission_transaction_id ON vc_submission (transaction_id);

-- ---- verify-vp_submission.sql ----
-- This Source Code Form is subject to the terms of the Mozilla Public
-- License, v. 2.0. If a copy of the MPL was not distributed with this
-- file, You can obtain one at https://mozilla.org/MPL/2.0/.
--
-- Table required by the embedded inji-verify library.
-- Stores VP submissions from the wallet during the presentation-during-issuance flow.

CREATE TABLE IF NOT EXISTS vp_submission (
    request_id              character varying(40) NOT NULL,
    vp_token                VARCHAR NULL,
    presentation_submission text NULL,
    error                   character varying(100) NULL,
    error_description       character varying(200) NULL,
    response_code           character varying(200) NULL,
    response_code_expiry_at TIMESTAMP WITH TIME ZONE NULL,
    response_code_used      boolean DEFAULT false,
    CONSTRAINT pk_vp_submission PRIMARY KEY (request_id),
    CONSTRAINT uq_vp_submission_response_code UNIQUE (response_code)
);

COMMENT ON TABLE vp_submission IS 'Stores VP token submissions received by the embedded inji-verify library';
COMMENT ON COLUMN vp_submission.request_id IS 'Foreign key to authorization_request_details.request_id';
COMMENT ON COLUMN vp_submission.vp_token IS 'The VP token submitted by the wallet';
COMMENT ON COLUMN vp_submission.presentation_submission IS 'JSON presentation_submission descriptor from the wallet';
COMMENT ON COLUMN vp_submission.error IS 'Error code if the wallet reported an error';
COMMENT ON COLUMN vp_submission.error_description IS 'Human-readable error description from the wallet';
COMMENT ON COLUMN vp_submission.response_code IS 'Response code for same-device flows (not used in certify)';
COMMENT ON COLUMN vp_submission.response_code_expiry_at IS 'Expiry of the response code';
COMMENT ON COLUMN vp_submission.response_code_used IS 'Whether the response code has been consumed';

CREATE INDEX IF NOT EXISTS idx_vp_submission_response_code ON vp_submission (response_code);
