CREATE TABLE IF NOT EXISTS key_alias(
    id character varying(36) NOT NULL,
    app_id character varying(36) NOT NULL,
    ref_id character varying(128),
    key_gen_dtimes timestamp,
    key_expire_dtimes timestamp,
    status_code character varying(36),
    lang_code character varying(3),
    cr_by character varying(256) NOT NULL,
    cr_dtimes timestamp NOT NULL,
    upd_by character varying(256),
    upd_dtimes timestamp,
    is_deleted boolean DEFAULT FALSE,
    del_dtimes timestamp,
    cert_thumbprint character varying(100),
    uni_ident character varying(50),
    CONSTRAINT pk_keymals_id PRIMARY KEY (id),
    CONSTRAINT uni_ident_const UNIQUE (uni_ident)
);

CREATE TABLE  IF NOT EXISTS key_policy_def(
    app_id character varying(36) NOT NULL,
    key_validity_duration smallint,
    is_active boolean NOT NULL,
    pre_expire_days smallint,
    access_allowed character varying(1024),
    cr_by character varying(256) NOT NULL,
    cr_dtimes timestamp NOT NULL,
    upd_by character varying(256),
    upd_dtimes timestamp,
    is_deleted boolean DEFAULT FALSE,
    del_dtimes timestamp,
    CONSTRAINT pk_keypdef_id PRIMARY KEY (app_id)
);
CREATE TABLE  IF NOT EXISTS key_store(
	id character varying(36) NOT NULL,
	master_key character varying(36) NOT NULL,
	private_key character varying(2500) NOT NULL,
	certificate_data character varying NOT NULL,
	cr_by character varying(256) NOT NULL,
	cr_dtimes timestamp NOT NULL,
	upd_by character varying(256),
	upd_dtimes timestamp,
	is_deleted boolean DEFAULT FALSE,
	del_dtimes timestamp,
	CONSTRAINT pk_keystr_id PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS ca_cert_store(
	cert_id character varying(36) NOT NULL,
	cert_subject character varying(500) NOT NULL,
	cert_issuer character varying(500) NOT NULL,
	issuer_id character varying(36) NOT NULL,
	cert_not_before timestamp,
	cert_not_after timestamp,
	crl_uri character varying(120),
	cert_data character varying,
	cert_thumbprint character varying(100),
	cert_serial_no character varying(50),
	partner_domain character varying(36),
	cr_by character varying(256),
	cr_dtimes timestamp,
	upd_by character varying(256),
	upd_dtimes timestamp,
	is_deleted boolean DEFAULT FALSE,
	del_dtimes timestamp,
	ca_cert_type character varying(25),
	CONSTRAINT pk_cacs_id PRIMARY KEY (cert_id),
	CONSTRAINT cert_thumbprint_unique UNIQUE (cert_thumbprint,partner_domain)
);

CREATE TABLE IF NOT EXISTS rendering_template (
    id VARCHAR(128) NOT NULL,
    template VARCHAR NOT NULL,
    cr_dtimes timestamp NOT NULL,
    upd_dtimes timestamp,
    CONSTRAINT pk_rendertmp_id PRIMARY KEY (id)
);

-- Changed all `JSONB` and `TEXT[]` types to VARCHAR to make it work with H2 database
CREATE TABLE IF NOT EXISTS credential_config (
    -- mirrors db_scripts/inji_certify/ddl/certify-credential_config.sql (JSONB and TEXT[] as VARCHAR on H2)
    credential_config_key_id VARCHAR(2048) NOT NULL UNIQUE,
    config_id VARCHAR(255) NOT NULL,
    status VARCHAR(255),
    vc_template VARCHAR,
    doctype VARCHAR,
    sd_jwt_vct VARCHAR,
    context VARCHAR,
    credential_type VARCHAR,
    credential_format VARCHAR(255) NOT NULL,
    did_url VARCHAR,
    key_manager_app_id VARCHAR(36),
    key_manager_ref_id VARCHAR(128),
    signature_algo VARCHAR(36),
    signature_crypto_suite VARCHAR(128),
    sd_claim VARCHAR,
    display VARCHAR NOT NULL,
    display_order VARCHAR NOT NULL,
    scope VARCHAR(255) NOT NULL,
    cryptographic_binding_methods_supported VARCHAR NOT NULL,
    credential_signing_alg_values_supported VARCHAR NOT NULL,
    proof_types_supported VARCHAR NOT NULL,
    claims VARCHAR,
    mso_mdoc_claims VARCHAR,
    sd_jwt_claims VARCHAR,
    plugin_configurations VARCHAR,
    credential_status_purpose VARCHAR,
    qr_settings VARCHAR,
    qr_signature_algo VARCHAR,
    -- 1.1.0 (V1_1_0_000__config_v2_and_tenancy.sql): the v2 model beside the legacy columns
    tenant_id VARCHAR(64) NOT NULL DEFAULT 'default',
    format_config VARCHAR,
    signing_config VARCHAR,
    template_id VARCHAR(128),
    template_version INT,
    issuance_strategy VARCHAR(16) NOT NULL DEFAULT 'TEMPLATE',
    data_source_id VARCHAR(128),
    status_config VARCHAR,
    protocol_overrides VARCHAR,
    config_version SMALLINT NOT NULL DEFAULT 1,
    cr_dtimes TIMESTAMP NOT NULL,
    upd_dtimes TIMESTAMP,
    CONSTRAINT pk_config_id PRIMARY KEY (config_id)
);

-- Status lists (db_scripts/inji_certify/ddl/certify-status_list_*.sql, certify-credential_status_transaction.sql) on H2:
-- the PostgreSQL enum and SERIAL columns become VARCHAR and IDENTITY.
CREATE TABLE IF NOT EXISTS status_list_credential (
    id VARCHAR(255) PRIMARY KEY,
    vc_document VARCHAR NOT NULL,
    credential_type VARCHAR(100) NOT NULL,
    status_purpose VARCHAR(100),
    capacity_in_kb BIGINT,
    credential_status VARCHAR(50),
    cr_dtimes TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    upd_dtimes TIMESTAMP
);

CREATE TABLE IF NOT EXISTS status_list_available_indices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_list_credential_id VARCHAR(255) NOT NULL,
    list_index BIGINT NOT NULL,
    is_assigned BOOLEAN NOT NULL DEFAULT FALSE,
    cr_dtimes TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    upd_dtimes TIMESTAMP,
    CONSTRAINT fk_status_list_credential FOREIGN KEY (status_list_credential_id) REFERENCES status_list_credential(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT uq_list_id_and_index UNIQUE (status_list_credential_id, list_index)
);

CREATE TABLE IF NOT EXISTS credential_status_transaction (
    transaction_log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    credential_id VARCHAR(255),
    status_purpose VARCHAR(100),
    status_value BOOLEAN,
    status_list_credential_id VARCHAR(255),
    status_list_index BIGINT,
    cr_dtimes TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_dtimes TIMESTAMP,
    is_processed BOOLEAN NOT NULL DEFAULT FALSE
);

-- 1.1.0 (V1_1_0_000__config_v2_and_tenancy.sql): versioned templates, decoded from the base64 blob
CREATE TABLE IF NOT EXISTS credential_template (
    id VARCHAR(128) NOT NULL,
    version INT NOT NULL DEFAULT 1,
    tenant_id VARCHAR(64) NOT NULL DEFAULT 'default',
    engine VARCHAR(32) NOT NULL,
    mode VARCHAR(16) NOT NULL,
    content VARCHAR NOT NULL,
    checksum VARCHAR(64),
    cr_dtimes TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_credential_template PRIMARY KEY (id, version)
);

-- 1.1.0: one row per issuance on the new surface
CREATE TABLE IF NOT EXISTS issuance_transaction (
    id UUID NOT NULL,
    tenant_id VARCHAR(64) NOT NULL DEFAULT 'default',
    access_token_hash VARCHAR(255),
    credential_config_id VARCHAR(2048),
    protocol_version VARCHAR(32),
    state VARCHAR(16) NOT NULL,
    holder_bindings VARCHAR,
    notification_id VARCHAR(128),
    credential_ids VARCHAR,
    cr_dtimes TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP,
    CONSTRAINT pk_issuance_transaction PRIMARY KEY (id)
);

-- presentation during issuance and the authorization code flow keep their sessions and codes here (mirrors db_scripts/inji_certify/ddl/certify-iar_session.sql)
CREATE TABLE IF NOT EXISTS iar_session (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    auth_session VARCHAR(128) NOT NULL UNIQUE,
    transaction_id VARCHAR(64) NOT NULL,
    request_id VARCHAR(64),
    verify_nonce VARCHAR(64),
    expires_at TIMESTAMP,
    client_id VARCHAR(128),
    scope VARCHAR(128),
    authorization_code VARCHAR(128),
    response_uri VARCHAR(512),
    code_challenge VARCHAR(128),
    code_challenge_method VARCHAR(10),
    code_issued_at TIMESTAMP,
    is_code_used BOOLEAN NOT NULL DEFAULT FALSE,
    code_used_at TIMESTAMP,
    cr_dtimes TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    identity_data VARCHAR
);

-- the credential ledger (mirrors db_scripts/inji_certify/ddl/certify-ledger.sql; JSONB as JSON on H2); read by the VC-API status endpoint
CREATE TABLE IF NOT EXISTS ledger (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    credential_id VARCHAR(255),
    issuer_id VARCHAR(255) NOT NULL,
    issuance_date TIMESTAMP NOT NULL,
    expiration_date TIMESTAMP,
    credential_type VARCHAR(100) NOT NULL,
    indexed_attributes JSON,
    credential_status_details JSON,
    cr_dtimes TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_ledger_tracked_credential_id UNIQUE (credential_id)
);
