#!/usr/bin/env bash
# Generates the Flyway baseline migrations under certify-service/src/main/resources/db/migration/<module>/
# from the psql DDL files in db_scripts/inji_certify/ddl. Re-run only when the DDL snapshot changes;
# baselines are immutable once released (later changes are new versioned migrations).
set -euo pipefail
cd "$(dirname "$0")/.."
DDL=db_scripts/inji_certify/ddl
OUT=certify-service/src/main/resources/db/migration
emit() { # emit <module> <version> <description> <files...>
  local module=$1 version=$2 desc=$3; shift 3
  local file="$OUT/$module/V${version}__${desc}.sql"
  mkdir -p "$OUT/$module"
  {
    echo "-- Flyway baseline for the $module tables, generated by db_scripts/generate_flyway_baseline.sh"
    echo "-- from $DDL. Do not edit: later schema changes are new versioned migrations."
    for f in "$@"; do echo; echo "-- ---- $f ----"; grep -v '^\\' "$DDL/$f"; done
  } > "$file"
  echo "wrote $file"
}
emit core       1_0_0_000 baseline_core certify-rendering_template.sql certify-credential_config.sql \
  certify-status_list_credential.sql certify-ledger.sql certify-credential_status_transaction.sql \
  certify-status_list_available_indices.sql certify-shedlock.sql
emit keymanager 1_0_0_001 baseline_keymanager certify-key_alias.sql certify-key_policy_def.sql certify-key_store.sql certify-ca_cert_store.sql
emit verify     1_0_0_002 baseline_verify verify-authorization_request_details.sql verify-vc_submission.sql verify-vp_submission.sql
emit as         1_0_0_003 baseline_as certify-iar_session.sql
