package io.mosip.certify.keyprovider.jca;

import com.nimbusds.jose.crypto.impl.ECDSA;
import io.mosip.certify.signing.CertificateChain;
import io.mosip.certify.signing.KeyFilter;
import io.mosip.certify.signing.KeyProvider;
import io.mosip.certify.signing.KeyRef;
import io.mosip.certify.signing.KeyRequirement;
import io.mosip.certify.signing.PublicKeyDescriptor;
import io.mosip.certify.signing.SignatureAlgorithm;
import io.mosip.certify.signing.SigningException;
import io.mosip.certify.signing.SigningKey;
import org.bouncycastle.jce.provider.BouncyCastleProvider;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.GeneralSecurityException;
import java.security.KeyStore;
import java.security.PrivateKey;
import java.security.Security;
import java.security.Signature;
import java.security.cert.Certificate;
import java.security.cert.X509Certificate;
import java.security.interfaces.ECPublicKey;
import java.security.interfaces.RSAPublicKey;
import java.security.spec.PSSParameterSpec;
import java.security.spec.MGF1ParameterSpec;
import java.util.ArrayList;
import java.util.Collections;
import java.util.EnumSet;
import java.util.Enumeration;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;

/**
 * A {@link KeyProvider} whose keys are JCA keys in memory: loaded from a PKCS#12 keystore, from PEM files, or
 * generated by {@link #devMode()} for development, tests, conformance runs and the CLI. It needs no database
 * and no keymanager; the private handle of every {@link SigningKey} is the JCA {@link PrivateKey}.
 */
public class JcaKeyProvider implements KeyProvider {

    public static final String ID = "jca";

    static {
        if (Security.getProvider(BouncyCastleProvider.PROVIDER_NAME) == null) {
            Security.addProvider(new BouncyCastleProvider());
        }
    }

    /** One key as held by this provider. */
    record Entry(String alias, PrivateKey privateKey, PublicKeyDescriptor descriptor) {}

    private final String id;
    private final Map<String, Entry> entries = new LinkedHashMap<>();

    public JcaKeyProvider() {
        this(ID);
    }

    public JcaKeyProvider(String id) {
        this.id = id;
    }

    /** Loads every key entry of a PKCS#12 keystore; the purpose of each key is {@code vc-signing}. */
    public static JcaKeyProvider fromPkcs12(Path path, char[] password) {
        try (InputStream in = Files.newInputStream(path)) {
            KeyStore keyStore = KeyStore.getInstance("PKCS12");
            keyStore.load(in, password);
            return fromKeyStore(keyStore, password);
        } catch (IOException | GeneralSecurityException e) {
            throw new SigningException("Cannot load PKCS#12 keystore " + path, e);
        }
    }

    public static JcaKeyProvider fromKeyStore(KeyStore keyStore, char[] password) {
        JcaKeyProvider provider = new JcaKeyProvider();
        try {
            Enumeration<String> aliases = keyStore.aliases();
            while (aliases.hasMoreElements()) {
                String alias = aliases.nextElement();
                if (!keyStore.isKeyEntry(alias)) {
                    continue;
                }
                PrivateKey privateKey = (PrivateKey) keyStore.getKey(alias, password);
                Certificate[] chain = keyStore.getCertificateChain(alias);
                List<X509Certificate> x509 = new ArrayList<>();
                if (chain != null) {
                    for (Certificate c : chain) {
                        x509.add((X509Certificate) c);
                    }
                }
                if (x509.isEmpty()) {
                    throw new SigningException("Keystore entry " + alias + " has no certificate");
                }
                provider.add(alias, privateKey, new CertificateChain(x509), null, "vc-signing");
            }
        } catch (GeneralSecurityException e) {
            throw new SigningException("Cannot read keystore", e);
        }
        return provider;
    }

    /**
     * Generates one key per algorithm with a self-signed certificate, aliased {@code dev-<alg>} in lower case
     * ({@code dev-es256}, {@code dev-eddsa}, {@code dev-rs256}, {@code dev-ps256}, {@code dev-es256k}).
     * Never use these keys outside development.
     */
    public static JcaKeyProvider devMode() {
        JcaKeyProvider provider = new JcaKeyProvider();
        for (SignatureAlgorithm alg : List.of(SignatureAlgorithm.ES256, SignatureAlgorithm.EdDSA, SignatureAlgorithm.RS256,
                SignatureAlgorithm.PS256, SignatureAlgorithm.ES256K)) {
            provider.generate("dev-" + alg.joseName().toLowerCase(), alg, "CN=Inji Certify dev " + alg.joseName(), "vc-signing");
        }
        return provider;
    }

    /** Generates a key with a self-signed certificate under the given alias. */
    public SigningKey generate(String alias, SignatureAlgorithm algorithm, String subjectDn, String purpose) {
        DevKeys.Generated generated = DevKeys.generate(algorithm, subjectDn);
        add(alias, generated.privateKey(), CertificateChain.of(generated.certificate()), algorithm, purpose);
        return resolve(new KeyRef(id, alias));
    }

    /**
     * Adds a key with its chain. The algorithm is derived from the key when {@code algorithm} is null:
     * RSA keys default to RS256, EC keys to the curve's ES algorithm, Ed25519 keys to EdDSA.
     */
    public void add(String alias, PrivateKey privateKey, CertificateChain chain, SignatureAlgorithm algorithm, String purpose) {
        X509Certificate leaf = chain.leaf().orElseThrow(() -> new SigningException("Alias " + alias + " needs a certificate"));
        SignatureAlgorithm alg = algorithm != null ? algorithm : DevKeys.algorithmFor(leaf.getPublicKey());
        String kid = alias;
        PublicKeyDescriptor descriptor = new PublicKeyDescriptor(kid, alg, leaf.getPublicKey(), chain,
                leaf.getNotBefore().toInstant(), leaf.getNotAfter().toInstant(), purpose);
        entries.put(alias, new Entry(alias, privateKey, descriptor));
    }

    /** Writes every key into a PKCS#12 keystore, e.g. to persist dev-mode keys between runs. */
    public void saveAsPkcs12(Path path, char[] password) {
        try {
            KeyStore keyStore = KeyStore.getInstance("PKCS12");
            keyStore.load(null, null);
            for (Entry entry : entries.values()) {
                keyStore.setKeyEntry(entry.alias(), entry.privateKey(), password,
                        entry.descriptor().chain().leafFirst().toArray(new Certificate[0]));
            }
            try (OutputStream out = Files.newOutputStream(path)) {
                keyStore.store(out, password);
            }
        } catch (IOException | GeneralSecurityException e) {
            throw new SigningException("Cannot write PKCS#12 keystore " + path, e);
        }
    }

    @Override
    public String id() {
        return id;
    }

    @Override
    public SigningKey resolve(KeyRef ref) {
        if (!id.equals(ref.provider())) {
            throw new SigningException("KeyRef " + ref + " is not for provider " + id);
        }
        Entry entry = entries.get(ref.alias());
        if (entry == null) {
            throw new SigningException("No key with alias '" + ref.alias() + "' in provider " + id);
        }
        return new SigningKey(ref, entry.descriptor(), entry.privateKey());
    }

    @Override
    public List<PublicKeyDescriptor> publicKeys(KeyFilter filter) {
        KeyFilter f = filter == null ? KeyFilter.ALL : filter;
        return entries.values().stream().map(Entry::descriptor).filter(f::matches).toList();
    }

    @Override
    public Set<SignatureAlgorithm> supportedAlgorithms() {
        return EnumSet.allOf(SignatureAlgorithm.class);
    }

    @Override
    public void ensureKeys(List<KeyRequirement> required) {
        for (KeyRequirement requirement : required) {
            if (!entries.containsKey(requirement.alias())) {
                generate(requirement.alias(), requirement.algorithm(), "CN=Inji Certify " + requirement.alias(), requirement.purpose());
            }
        }
    }

    public Set<String> aliases() {
        return Collections.unmodifiableSet(entries.keySet());
    }

    @Override
    public byte[] signRaw(byte[] data, SigningKey key, SignatureAlgorithm algorithm) {
        if (!(key.providerHandle() instanceof PrivateKey privateKey)) {
            throw new SigningException("Key " + key.ref() + " was not resolved by provider " + id);
        }
        checkKeyMatches(key, algorithm);
        try {
            Signature signature = algorithm.isRsa() || algorithm.isEc()
                    ? Signature.getInstance(algorithm.jcaName(), BouncyCastleProvider.PROVIDER_NAME)
                    : Signature.getInstance(algorithm.jcaName());
            if (algorithm == SignatureAlgorithm.PS256) {
                signature.setParameter(new PSSParameterSpec("SHA-256", "MGF1", MGF1ParameterSpec.SHA256, 32, 1));
            }
            signature.initSign(privateKey);
            signature.update(data);
            byte[] raw = signature.sign();
            if (algorithm.isEc()) {
                return ECDSA.transcodeSignatureToConcat(raw, algorithm.concatLength());
            }
            return raw;
        } catch (GeneralSecurityException | com.nimbusds.jose.JOSEException e) {
            throw new SigningException("Signing with " + key.ref() + " failed", e);
        }
    }

    private static void checkKeyMatches(SigningKey key, SignatureAlgorithm algorithm) {
        var publicKey = key.descriptor().publicKey();
        boolean ok = switch (algorithm) {
            case RS256, PS256 -> publicKey instanceof RSAPublicKey;
            case ES256, ES256K, ES384, ES512 -> publicKey instanceof ECPublicKey;
            case EdDSA -> "Ed25519".equalsIgnoreCase(publicKey.getAlgorithm()) || "EdDSA".equalsIgnoreCase(publicKey.getAlgorithm());
        };
        if (!ok) {
            throw new SigningException("Key " + key.ref() + " (" + publicKey.getAlgorithm() + ") cannot sign with " + algorithm.joseName());
        }
    }

    Optional<Entry> entry(String alias) {
        return Optional.ofNullable(entries.get(alias));
    }
}
